<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ClipboardTool.Tools.E2eT07</RootNamespace>
    <AssemblyName>E2eT07</AssemblyName>
  </PropertyGroup>

</Project>
